### PR TITLE
Properly support yaw rate command integration from controller

### LINKED ISSUE #25: Bug in ServoDyn When Controlling Yaw from DLL
In routine CalculateStandardYaw of ServoDyn.f90, the yaw angle (position) command when the yaw rate is commanded from a Bladed-style DLL is calculated by adding an increment of YawRateCom*DT to the current yaw angle. However, the yaw angle command should be defined as the integral of the yaw rate command, regardless of the current yaw angle (i.e. the yaw angle command must become a state of ServoDyn). As it is currently implemented (incorrectly), when the yaw rate commanded from a Bladed-style DLL is zero, the yaw angle is commanded to be current yaw angle, effectively eliminating the yaw spring stiffness, yielding large yaw errors. I would not use yaw control from Bladed-style DLL controllers until this bug is fixed.

See the following forum topic for more information: https://wind.nrel.gov/forum/wind/viewtopic.php?f=30&t=1844&p=9256.

### PR DESCRIPTION
**Pull request by andrew-platt**
THIS PULL REQUEST __IS__ READY TO MERGE

**Feature or improvement description**
Integration of the yawrate command from the DLL is now properly supported.
This has been tested by @nikhar-abbas and @ewquon

**Related issue, if one exists**
Issue #25 

**Impacted areas of the software**
This resolves issue #25.  When a DLL was controlling the yaw, the position was incorrectly integrated.

**Test results, if applicable**
No test cases are affected by this PR as none of the glue-code DLL cases use yaw control.

Closes #25

### CODE REVIEW

File: modules/servodyn/src/ServoDyn.f90 [hunk 1]
```diff
@@ -2954,7 +2973,7 @@ SUBROUTINE Yaw_UpdateStates( t, u, p, x, xd, z, OtherState, m, ErrStat, ErrMsg )
 
       IF ( .not. OtherState%BegYawMan )  THEN  ! Override yaw maneuver is just beginning (possibly again).
 
-         CALL CalculateStandardYaw(t, u, p, m, YawPosCom, YawRateCom, ErrStat, ErrMsg)
+         CALL CalculateStandardYaw(t, u, p, m, YawPosCom, YawRateCom, OtherState%YawPosComInt, ErrStat, ErrMsg)
```
Comment (bjonkman) [inline modules/servodyn/src/ServoDyn.f90:2976]: It looks like you could potentially be updating the OtherState%YawPosComInt twice in this call (i.e., taking two steps instead of just one).

File: modules/servodyn/src/ServoDyn.f90 [hunk 2]
```diff
@@ -464,6 +464,11 @@ SUBROUTINE SrvD_Init( InitInp, u, p, x, xd, z, OtherState, y, m, Interval, InitO
    OtherState%TTpBrFl = HUGE(OtherState%TTpBrFl) !basically never deploy them. Eventually this will be added back?
    !OtherState%TTpBrFl = InputFileData%TTpBrFl + p%TpBrDT
 
+
+      !............................................................................................
+      ! yaw control integrated command angle
+      !............................................................................................
+   OtherState%YawPosComInt = p%YawNeut
```
Comment (bjonkman) [inline modules/servodyn/src/ServoDyn.f90:472]: Do we need to take into account the initial yaw position from ElastoDyn here?

File: modules/servodyn/src/ServoDyn.f90 (hunk 1 above)
Comment (andrew-platt) [reply modules/servodyn/src/ServoDyn.f90:2976]: I missed this bit of logic.  The second call to `CalculateStandadYaw` is during an override yaw manuever and should only be called once while `OtherState%BegYawMan` is false.  If we are doing an over-ride of the yaw from the DLL, I would expect the DLL commanded yaw should be completely out of the loop then, so maybe the first first `CalculateStandardYaw should be in an `else` condition on `t >= p%TYawManS`.
